### ISSUE TITLE
Add 4.02.0 to chocolatey

### ISSUE THREAD

**Issue by gabelevi** [andyli/ocpwin-choco#1]
https://chocolatey.org/packages/ocpwin currently only has 4.02.0. I see you have a commit in this repository for 4.02.0. Is it possible to submit 4.02.0 to chocolately too?

**Comment by andyli** [comment]
Submitted -> https://chocolatey.org/packages/ocpwin/4.02.1.20160113
Keeping this issue open until the package has been approved. ;)

**Comment by andyli** [comment]
Approved :)
